name: make-docker

on: [push, workflow_dispatch]

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: redlib
      TARGET: aarch64-unknown-linux-musl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ github.ref }}-
            ${{ runner.os }}-cargo-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
          platforms: linux/arm64
          build-args: |
            TARGET=${{ env.TARGET }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:cache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}:cache,mode=max
